gemfile:
  - gemfiles/Gemfile.rails-3.0.rb
  - gemfiles/Gemfile.rails-3.1.rb
  - gemfiles/Gemfile.rails-3.2.rb
  - gemfiles/Gemfile.rails-4.0.rb
script: bundle exec rspec spec
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.rails-4.0.rb
    - rvm: ree
      gemfile: gemfiles/Gemfile.rails-4.0.rb
